<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMvTCx7J\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMvTCx7J/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMvTCx7J.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMvTCx7J\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMvTCx7J\App_KernelDevDebugContainer([
    'container.build_hash' => 'MvTCx7J',
    'container.build_id' => '3a7f42ed',
    'container.build_time' => 1763904752,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMvTCx7J');
