<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU7UTqF3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU7UTqF3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU7UTqF3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU7UTqF3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU7UTqF3\App_KernelDevDebugContainer([
    'container.build_hash' => 'U7UTqF3',
    'container.build_id' => 'f9538a4c',
    'container.build_time' => 1763737969,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU7UTqF3');
