<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'cow_index' => [[], ['_controller' => 'App\\Controller\\CowController::index'], [], [['text', '/gado']], [], [], []],
    'cow_add' => [[], ['_controller' => 'App\\Controller\\CowController::addCow'], [], [['text', '/gado/adicionar']], [], [], []],
    'cow_edit' => [['id'], ['_controller' => 'App\\Controller\\CowController::editCow'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/gado/editar']], [], [], []],
    'farm_index' => [[], ['_controller' => 'App\\Controller\\FarmController::index'], [], [['text', '/fazenda']], [], [], []],
    'farm_add' => [[], ['_controller' => 'App\\Controller\\FarmController::addFarm'], [], [['text', '/fazenda/adicionar']], [], [], []],
    'farm_edit' => [['id'], ['_controller' => 'App\\Controller\\FarmController::editFarm'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/fazenda/editar']], [], [], []],
    'farm_remove' => [['id'], ['_controller' => 'App\\Controller\\FarmController::removeFarm'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/fazenda/apagar']], [], [], []],
    'veterinarian_index' => [[], ['_controller' => 'App\\Controller\\VeterinarianController::index'], [], [['text', '/veterinario']], [], [], []],
    'veterinarian_add' => [[], ['_controller' => 'App\\Controller\\VeterinarianController::addVeterinarian'], [], [['text', '/veterinario/adicionar']], [], [], []],
    'veterinarian_edit' => [['id'], ['_controller' => 'App\\Controller\\VeterinarianController::editVeterinarian'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/veterinario/editar']], [], [], []],
    'veterinarian_remove' => [['id'], ['_controller' => 'App\\Controller\\VeterinarianController::removeVeterinarian'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/veterinario/apagar']], [], [], []],
    'App\Controller\CowController::index' => [[], ['_controller' => 'App\\Controller\\CowController::index'], [], [['text', '/gado']], [], [], []],
    'App\Controller\CowController::addCow' => [[], ['_controller' => 'App\\Controller\\CowController::addCow'], [], [['text', '/gado/adicionar']], [], [], []],
    'App\Controller\CowController::editCow' => [['id'], ['_controller' => 'App\\Controller\\CowController::editCow'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/gado/editar']], [], [], []],
    'App\Controller\FarmController::index' => [[], ['_controller' => 'App\\Controller\\FarmController::index'], [], [['text', '/fazenda']], [], [], []],
    'App\Controller\FarmController::addFarm' => [[], ['_controller' => 'App\\Controller\\FarmController::addFarm'], [], [['text', '/fazenda/adicionar']], [], [], []],
    'App\Controller\FarmController::editFarm' => [['id'], ['_controller' => 'App\\Controller\\FarmController::editFarm'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/fazenda/editar']], [], [], []],
    'App\Controller\FarmController::removeFarm' => [['id'], ['_controller' => 'App\\Controller\\FarmController::removeFarm'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/fazenda/apagar']], [], [], []],
    'App\Controller\VeterinarianController::index' => [[], ['_controller' => 'App\\Controller\\VeterinarianController::index'], [], [['text', '/veterinario']], [], [], []],
    'App\Controller\VeterinarianController::addVeterinarian' => [[], ['_controller' => 'App\\Controller\\VeterinarianController::addVeterinarian'], [], [['text', '/veterinario/adicionar']], [], [], []],
    'App\Controller\VeterinarianController::editVeterinarian' => [['id'], ['_controller' => 'App\\Controller\\VeterinarianController::editVeterinarian'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/veterinario/editar']], [], [], []],
    'App\Controller\VeterinarianController::removeVeterinarian' => [['id'], ['_controller' => 'App\\Controller\\VeterinarianController::removeVeterinarian'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/veterinario/apagar']], [], [], []],
];
